module.exports = {
  API_KEY: "OP4C27j7bTvUJdk0HZMMtxOMwEpLmQdqEOob57oi2p6ujLtLq0v1hRBjMARhvZTD",
  SECRET_KEY:
    "ytGfQ0jolkjMf9aIdbd6N9ovF2qfvcZ7sgy2THj4knRS2ARLS9De4dtsudAS55BB",
  SYMBOL: "BNBUSDT",
  POSITION_SIZE: 0.01,
  NUM_BUY_GRID_LINES: 5,
  NUM_SELL_GRID_LINES: 5,
  GRID_SIZE: 0.25,
  CHECK_ORDERS_FREQUENCY: 1,
  CLOSED_ORDER_STATUS: "closed",
};
